"""Add last_online to student

Revision ID: 0292c01b6cac
Revises: 61db2ae0dc93
Create Date: 2020-03-04 20:38:06.864868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0292c01b6cac'
down_revision = '61db2ae0dc93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_section_student', sa.Column('last_online', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_section_student', 'last_online')
    # ### end Alembic commands ###
