"""Add 'online mode' table

Revision ID: 054b46d581ab
Revises: 6e3156596612
Create Date: 2020-03-14 15:23:41.510586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054b46d581ab'
down_revision = '6e3156596612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('online_mode',
    sa.Column('online_mode', sa.String(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('online_mode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('online_mode')
    # ### end Alembic commands ###
