"""add form_distribution_id to form_response and archived_at to form_question

Revision ID: 16015ee95119
Revises: 8c7aa2a3c62e
Create Date: 2020-02-15 09:48:24.806063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16015ee95119'
down_revision = '8c7aa2a3c62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_question', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_question', 'archived_at')
    # ### end Alembic commands ###
