"""Add archived_at to questions

Revision ID: 24d87e41078e
Revises: 6a99c159e06c
Create Date: 2020-02-17 13:02:53.117027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d87e41078e'
down_revision = '6a99c159e06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'archived_at')
    # ### end Alembic commands ###
