"""Add index to form_question

Revision ID: 29fa27ca16a4
Revises: 74483142c19a
Create Date: 2020-02-17 10:09:15.417796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fa27ca16a4'
down_revision = '74483142c19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_question', sa.Column('index_in_form', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_question', 'index_in_form')
    # ### end Alembic commands ###
