"""Add matching algorithm table

Revision ID: 2a3b80abe9bb
Revises: be37c40a36c3
Create Date: 2020-02-27 18:17:13.739063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3b80abe9bb'
down_revision = 'be37c40a36c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_algorithm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_algorithm_current'), 'matching_algorithm', ['current'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matching_algorithm_current'), table_name='matching_algorithm')
    op.drop_table('matching_algorithm')
    # ### end Alembic commands ###
