"""Update heartbeat table so heartbeats can be updated

Revision ID: 35c76fec63e1
Revises: a8acc0331a49
Create Date: 2020-03-05 21:27:40.121843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35c76fec63e1'
down_revision = 'a8acc0331a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_heartbeat', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('student_heartbeat', sa.Column('last_updated', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_student_heartbeat_student_id'), 'student_heartbeat', ['student_id'], unique=False)
    op.drop_column('student_heartbeat', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_heartbeat', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_student_heartbeat_student_id'), table_name='student_heartbeat')
    op.drop_column('student_heartbeat', 'last_updated')
    op.drop_column('student_heartbeat', 'created_at')
    # ### end Alembic commands ###
