"""Add 'cancelled' to request status

Revision ID: 37811d27b734
Revises: 054b46d581ab
Create Date: 2020-03-15 17:23:09.028706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37811d27b734'
down_revision = '054b46d581ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tutoring_session_guide_id'), 'tutoring_session', ['guide_id'], unique=False)
    op.create_index(op.f('ix_tutoring_session_learner_id'), 'tutoring_session', ['learner_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TYPE sessionrequeststatus ADD VALUE 'cancelled'")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutoring_session_learner_id'), table_name='tutoring_session')
    op.drop_index(op.f('ix_tutoring_session_guide_id'), table_name='tutoring_session')
    # ### end Alembic commands ###
