"""Make session id on form_response not nullable

Revision ID: 40f6977ec0bf
Revises: d99bd085cddc
Create Date: 2020-02-17 16:35:14.531274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f6977ec0bf'
down_revision = 'd99bd085cddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_response', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_response', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
