"""Remove applicable_date from form_distribution

Revision ID: 4aaa5ba83bf5
Revises: 24d87e41078e
Create Date: 2020-02-17 13:48:43.408752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4aaa5ba83bf5'
down_revision = '24d87e41078e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('class_date_index', table_name='form_distribution')
    op.drop_column('form_distribution', 'applicable_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_distribution', sa.Column('applicable_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index('class_date_index', 'form_distribution', ['class_section_id', 'applicable_date'], unique=False)
    # ### end Alembic commands ###
