"""Add device ID to student heartbeat

Revision ID: 5a7c49fafea2
Revises: 715b4be384fd
Create Date: 2020-03-05 21:56:15.844275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7c49fafea2'
down_revision = '715b4be384fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_heartbeat', sa.Column('device_id', sa.String(), nullable=False))
    op.create_index('student_device_index', 'student_heartbeat', ['student_id', 'device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('student_device_index', table_name='student_heartbeat')
    op.drop_column('student_heartbeat', 'device_id')
    # ### end Alembic commands ###
