"""Remove args from matching algorithm (need to change to JSON)

Revision ID: 5bf7b73b0d92
Revises: fd10e2f85692
Create Date: 2020-02-29 16:20:04.807282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bf7b73b0d92'
down_revision = 'fd10e2f85692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_algorithm', 'args')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_algorithm', sa.Column('args', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
