"""Add args to matching algorithm, as JSON

Revision ID: 61db2ae0dc93
Revises: 5bf7b73b0d92
Create Date: 2020-02-29 16:20:40.097916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61db2ae0dc93'
down_revision = '5bf7b73b0d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_algorithm', sa.Column('args', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_algorithm', 'args')
    # ### end Alembic commands ###
