"""Add student ID to form response

Revision ID: 6a99c159e06c
Revises: 29fa27ca16a4
Create Date: 2020-02-17 12:13:00.825654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a99c159e06c'
down_revision = '29fa27ca16a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_response', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_form_response_student_id'), 'form_response', ['student_id'], unique=False)
    op.create_foreign_key(None, 'form_response', 'class_section_student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_response', type_='foreignkey')
    op.drop_index(op.f('ix_form_response_student_id'), table_name='form_response')
    op.drop_column('form_response', 'student_id')
    # ### end Alembic commands ###
