"""Add online mode to tutoring sessions

Revision ID: 6e3156596612
Revises: 5a7c49fafea2
Create Date: 2020-03-14 15:08:20.230993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e3156596612'
down_revision = '5a7c49fafea2'
branch_labels = None
depends_on = None


def upgrade():
    sessionrequeststatus = postgresql.ENUM('not_applicable', 'pending', 'accepted', 'rejected', name='sessionrequeststatus')
    sessionrequeststatus.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutoring_session', sa.Column('conference_link', sa.String(), nullable=True))
    op.add_column('tutoring_session', sa.Column('rejection_note', sa.String(), nullable=True))
    op.add_column('tutoring_session', sa.Column('request_status', sa.Enum('not_applicable', 'pending', 'accepted', 'rejected', name='sessionrequeststatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutoring_session', 'request_status')
    op.drop_column('tutoring_session', 'rejection_note')
    op.drop_column('tutoring_session', 'conference_link')
    # ### end Alembic commands ###

    sessionrequeststatus = postgresql.ENUM('not_applicable', 'pending', 'accepted', 'rejected', name='sessionrequeststatus')
    sessionrequeststatus.drop(op.get_bind())
