"""Add index to student_heartbeat.last_updated

Revision ID: 715b4be384fd
Revises: 35c76fec63e1
Create Date: 2020-03-05 21:28:28.120439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715b4be384fd'
down_revision = '35c76fec63e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_student_heartbeat_last_updated'), 'student_heartbeat', ['last_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_heartbeat_last_updated'), table_name='student_heartbeat')
    # ### end Alembic commands ###
