"""Add form_distribution_id to form-response (for real)

Revision ID: 74483142c19a
Revises: 16015ee95119
Create Date: 2020-02-15 10:23:26.457882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74483142c19a'
down_revision = '16015ee95119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_response', sa.Column('form_distribution_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_form_response_form_distribution_id'), 'form_response', ['form_distribution_id'], unique=False)
    op.create_foreign_key(None, 'form_response', 'form_distribution', ['form_distribution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_response', type_='foreignkey')
    op.drop_index(op.f('ix_form_response_form_distribution_id'), table_name='form_response')
    op.drop_column('form_response', 'form_distribution_id')
    # ### end Alembic commands ###
