"""Remove original_question from form responses

Revision ID: 8c7aa2a3c62e
Revises: 1f3ddc1d481e
Create Date: 2020-02-13 22:10:07.132619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7aa2a3c62e'
down_revision = '1f3ddc1d481e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_response', 'original_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_response', sa.Column('original_question', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
