"""Add args to matching algorithm

Revision ID: 8e1d5c18acdb
Revises: 2a3b80abe9bb
Create Date: 2020-02-28 20:09:44.646690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1d5c18acdb'
down_revision = '2a3b80abe9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_algorithm', sa.Column('args', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_algorithm', 'args')
    # ### end Alembic commands ###
