"""Add original question index to response

Revision ID: 94abd030f196
Revises: bcdfd6bd3d3a
Create Date: 2020-02-17 16:50:53.981635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94abd030f196'
down_revision = 'bcdfd6bd3d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_response', sa.Column('original_question_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_response', 'original_question_index')
    # ### end Alembic commands ###
