"""empty message

Revision ID: 97123312d20a
Revises: aa71c74bec6e
Create Date: 2020-02-11 19:15:08.450037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97123312d20a'
down_revision = 'aa71c74bec6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutoring_session', sa.Column('skill', sa.String(), nullable=True))
    op.create_index(op.f('ix_tutoring_session_skill'), 'tutoring_session', ['skill'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutoring_session_skill'), table_name='tutoring_session')
    op.drop_column('tutoring_session', 'skill')
    # ### end Alembic commands ###
