"""Create heartbeat table

Revision ID: a8acc0331a49
Revises: 0292c01b6cac
Create Date: 2020-03-05 21:23:44.457851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8acc0331a49'
down_revision = '0292c01b6cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['class_section_student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('class_section_student', 'last_online')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_section_student', sa.Column('last_online', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('student_heartbeat')
    # ### end Alembic commands ###
