"""Add index to ka_skill_completion.created_at

Revision ID: aa71c74bec6e
Revises: b42c391cf38d
Create Date: 2020-02-11 18:30:20.334802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa71c74bec6e'
down_revision = 'b42c391cf38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ka_skill_completion_created_at'), 'ka_skill_completion', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ka_skill_completion_created_at'), table_name='ka_skill_completion')
    # ### end Alembic commands ###
