"""Add created_at to responses

Revision ID: afc84044c1e8
Revises: 94abd030f196
Create Date: 2020-02-17 16:54:57.476324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc84044c1e8'
down_revision = '94abd030f196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_response', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_response', 'created_at')
    # ### end Alembic commands ###
