"""Add created_at to session_learner_form_response

Revision ID: b42c391cf38d
Revises: 508b5d9e042a
Create Date: 2020-02-10 21:40:40.446227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42c391cf38d'
down_revision = '508b5d9e042a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_learner_form_response', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_learner_form_response', 'created_at')
    # ### end Alembic commands ###
