"""Remove old form stuff

Revision ID: b8db000dbee9
Revises: afc84044c1e8
Create Date: 2020-02-23 18:28:32.927366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8db000dbee9'
down_revision = 'afc84044c1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_learner_form_response_session_id', table_name='session_learner_form_response')
    op.drop_table('session_learner_form_response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_learner_form_response',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutoring_session.id'], name='session_learner_form_response_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='session_learner_form_response_pkey')
    )
    op.create_index('ix_session_learner_form_response_session_id', 'session_learner_form_response', ['session_id'], unique=False)
    # ### end Alembic commands ###
