"""Add unique constraint for class/date to form_distribution

Revision ID: c6b71c4167a1
Revises: d3a4402a7d62
Create Date: 2020-02-17 16:06:20.948398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b71c4167a1'
down_revision = 'd3a4402a7d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_class_date_uc', 'form_distribution', ['class_section_id', 'applicable_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_class_date_uc', 'form_distribution', type_='unique')
    # ### end Alembic commands ###
