"""Add index to session_learner_form_response.session_id

Revision ID: ce07d94ddbb5
Revises: 97123312d20a
Create Date: 2020-02-11 20:31:55.330017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce07d94ddbb5'
down_revision = '97123312d20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_session_learner_form_response_session_id'), 'session_learner_form_response', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_learner_form_response_session_id'), table_name='session_learner_form_response')
    # ### end Alembic commands ###
