"""form tables

Revision ID: f9bb9ba38094
Revises: ce07d94ddbb5
Create Date: 2020-02-12 20:58:50.599680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9bb9ba38094'
down_revision = 'ce07d94ddbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('question_type', sa.Enum('short_text', 'long_text', 'multiple_choice', 'linear_scale', name='questiontype'), nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('applicable_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_section.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('class_date_index', 'form_distribution', ['class_section_id', 'applicable_date'], unique=False)
    op.create_table('form_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_question_form_id'), 'form_question', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_question_question_id'), 'form_question', ['question_id'], unique=False)
    op.create_table('form_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_question_id', sa.Integer(), nullable=False),
    sa.Column('original_question', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_question_id'], ['form_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_response_form_question_id'), 'form_response', ['form_question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_response_form_question_id'), table_name='form_response')
    op.drop_table('form_response')
    op.drop_index(op.f('ix_form_question_question_id'), table_name='form_question')
    op.drop_index(op.f('ix_form_question_form_id'), table_name='form_question')
    op.drop_table('form_question')
    op.drop_index('class_date_index', table_name='form_distribution')
    op.drop_table('form_distribution')
    op.drop_table('question')
    op.drop_table('form')
    # ### end Alembic commands ###
