"""Rename query to sql_query

Revision ID: fd10e2f85692
Revises: 8e1d5c18acdb
Create Date: 2020-02-28 23:51:12.504703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd10e2f85692'
down_revision = '8e1d5c18acdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_matching_algorithm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matching_algorithm_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matching_algorithm_id'], ['matching_algorithm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_matching_algorithm_archived_at'), 'active_matching_algorithm', ['archived_at'], unique=False)
    op.create_index(op.f('ix_active_matching_algorithm_key'), 'active_matching_algorithm', ['key'], unique=False)
    op.add_column('matching_algorithm', sa.Column('sql_query', sa.String(), nullable=False))
    op.drop_index('ix_matching_algorithm_current', table_name='matching_algorithm')
    op.drop_column('matching_algorithm', 'current')
    op.drop_column('matching_algorithm', 'query')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_algorithm', sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('matching_algorithm', sa.Column('current', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_matching_algorithm_current', 'matching_algorithm', ['current'], unique=False)
    op.drop_column('matching_algorithm', 'sql_query')
    op.drop_index(op.f('ix_active_matching_algorithm_key'), table_name='active_matching_algorithm')
    op.drop_index(op.f('ix_active_matching_algorithm_archived_at'), table_name='active_matching_algorithm')
    op.drop_table('active_matching_algorithm')
    # ### end Alembic commands ###
